### PR TITLE
Handle Sub-queries with mongodb additional features

### PR DESCRIPTION
**Pull request by sumeetchhetri**
# Core

KunderaQuery:
1. Added support for 'NOT IN' and '<>'
2. Added support for sub-queries - keywords '(' and ')'
3. The same column/parameter value pair may be repeated multiple times in a query, fixed this with the List<FilterClause> instead of single FilterClause
4. Fixed the tokenize function to ignore blank values
5. While adding INTER_CLAUSE_OPERATORS to the FilterClause queue make sure we trim the operators

QueryImpl:
1. Added support for setFirstResult (pagination)
# Mongodb Client

MongoDBClient:
1. Added support for pagination (skip) function in mongodb
2. Added support for count query

MongoDBDataHandler:
1. Added support for pagination (skip) function in mongodb

MongoDBQuery:
1. Added support for pagination (skip) function in mongodb
2. Added new QueryComponent class to handle subqueries based on AND/OR/(/)
3. Added support for 'IN', 'NOT IN' and '<>' for mongodb-client
4. Added support for '$inc' in the form of special UPDATE functions in mongodb-client

ResultIterator:
1. Resolved compilation error

### CODE REVIEW

**Comment by mevivs** [comment]
@sumeetchhetri 
Thanks! i will have a look on it. Btw just to confirm junits are also in place for suggested changes?

-Vivek

**Comment by sumeetchhetriwellogic** [comment]
Actually these are the changes that i am using in one of my projects, never really thought about the junit tests, let me have a look and i'll try and update the tests too.

**Comment by mevivs** [comment]
@sumeetchhetri 
Sure. Btw using Kundera for? Could you please spare few minutes to fill in for survey? Here it is
http://www.surveymonkey.com/s/BMB9PWG

**Comment by sumeetchhetriwellogic** [comment]
Point #3 - Consider the below query
select \* from table where (colA = :colA and colB = :colB) OR (colA = :colA and colC = :colC)
the List<FilterClause> fixes the issue with multiple colA parameters

There was some unnecessary code lying around in MongoDBQuery (removed all the trash from in there)

Also have updated the junit tests, made sure the tests pass

**Comment by sumeetchhetriwellogic** [comment]
DO let me know if i missed out anything...

**Comment by mevivs** [comment]
Looking into this. 
-Vivek

**Comment by mevivs** [comment]
Merged. Thanks for the contribution. Will get somebody to add more junits around this.

-Vivek

**Comment by chhavigangwal** [comment]
Fixed in Kundera-2.11.1

**Pull request merged**
