### PR TITLE
Issue 131 Resolution

### PR DESCRIPTION
**Pull request by phillipCouto**
I updated the test classes as they all had errors in them. The resolution for issue 131 is in the Reader class I removed some redundant code and added code to remove %20 from paths to prevent the incorrect path from being passed down.

### CODE REVIEW

**Comment by mevivs** [comment]
Few questions:
1) Reason for renaming these test classes?
2) Is there any other solution available, except:

```
                File f = new File(url.getPath().trim().replace("%20", " "));
```

Like to check for URL protocol, if it is for  to "jar" extension then only invoke `new JarFileIterator()` etc ?

3) Any test case available to validate this fix?

4) Kundera is building without any building with these changes?(mvn clean install)

**Comment by phillipCouto** [comment]
Well from my research if it was a jar file it would of been resolved further up the logic. When the application would enter at that point the URL would be a file resource which does not like %20 in the path.

**Comment by mevivs** [comment]
Hi Phillip,
Let me know, if it works for you with given below code snippet in Reader.java:

```

    /**
     * Gets the resource iterator.
     * 
     * @param url
     *            the url
     * @param filter
     *            the filter
     * 
     * @return the resource iterator
     * 
     * @throws IOException
     *             Signals that an I/O exception has occurred.
     */
    public ResourceIterator getResourceIterator(URL url, Filter filter)
    {
        String urlString = url.toString();
        try
        {
            if (urlString.endsWith("!/"))
            {
                urlString = urlString.substring(4);
                urlString = urlString.substring(0, urlString.length() - 2);
                url = new URL(urlString);
            }

            if (urlString.endsWith(".class"))
            {
                File f = new File(url.getPath());
                return new ClassFileIterator(f);
            }
            else if (!urlString.endsWith("/") && url.getProtocol().equals(AllowedProtocol.JAR.name()))
            {
                return new JarFileIterator(url.openStream(), filter);
            }
            else
            {
                if (!url.getProtocol().equals("file"))
                {
                    throw new ResourceReadingException("Unable to understand protocol: " + url.getProtocol());
                }

                File f = new File(url.getPath());
                if (f.isDirectory())
                {
                    return new ClassFileIterator(f, filter);
                }
                else
                {
                    return new JarFileIterator(url.openStream(), filter);
                }
            }
        }
        catch (MalformedURLException e)
        {
            throw new ResourceReadingException(e);
        }
        catch (IOException e)
        {
            throw new ResourceReadingException(e);
        }
    }
```

2.2 is releasing very soon, so any input from your side will make this in with this release.

-Vivek

**Comment by phillipCouto** [comment]
That does not work because the problem is the URL contains %20 instead of spaces and when it tries to create a File object with the URL path it always returns false when checking if it is a directory.

Here is what happens:
Classpath = C:\Users\Phillip Couto\workspace\CassandraTest\bin\classes

Kundera parses it as:
URL = C:\Users\Phillip%20Couto\workspace\CassandraTest\bin\classes

When the path is handed to the File object it does not convert the %20 to a space and actually looks for the path in the URL which does not exist.

When you are getting the path of the URL object the path needs to have the URL encoding removed or else the path will never exist. 

I know I can fix this by putting the code in a folder that has no spaces in the path but that's just avoiding the bug. 

Maybe what needs to be added is the URLDecoder decoding the URL into a valid file path before you continue to passing the path to a File Object.

``` Java
String filePath = URLDecoder.decode(url.getPath(), "UTF-8");
File f = new File(filePath);
```

**Comment by mevivs** [comment]
:+1: 

```
String filePath = URLDecoder.decode(url.getPath(), "UTF-8");
```

sounds good to me rather than "%20" check.

Could you please raise a pull request with your changes, if above stuff works for you?

What it should contain: 
1) A test case to demonstrate the fix
2) Code should get build(in your case "mvn clean install" over kundera/core project)

-Vivek

**Comment by phillipCouto** [comment]
Ok I implemented the change but mvn clean install fails because the RootURL is returning as "file:/C:/Users/Phillip%20Couto/git/Kundera/kundera-core/target/test-classes" but the test is looking for "/kundera-core/target/test-classes/" at the end.

The test that is failing is:
com.impetus.kundera.persistence.PersistenceUnitLoaderTest

The line of code is:

``` Java
Assert.assertTrue(metadatas.get(0).getPersistenceUnitRootUrl().getPath().endsWith(_pattern));
```

Looks like the JRE in windows does not like adding the final "/" to URLs. Would you like me to create the fix for this test aswell?

**Comment by mevivs** [comment]
Yes. I guess _pattern can be overridern based on OS settings as well.

**Comment by phillipCouto** [comment]
Should I overwrite pattern based on windows or should I do a check to see if the assertion fails and then try again without the final "/"? This way if JRE behaviour changes for other OSs it will still pass.

**Comment by mevivs** [comment]
I would prefer:

```
private static String OS = System.getProperty("os.name").toLowerCase();

public static boolean isWindows() {

        return (OS.indexOf("win") >= 0);

    }
```

-Vivek

**Pull request closed without merging**
