### PR TITLE
MongoDBDataHandler interface

### PR DESCRIPTION
**Pull request by bsideup**

### CODE REVIEW

**Comment by bsideup** [comment]
closed because of "git mv" issue

**Comment by bsideup** [comment]
My bad, eveything is fine, file history is available with "git log --follow". Reopening.

**Comment by mevivs** [comment]
Hi,
Could you please provide description(few lines) around this pull request?

-Vivek

**Comment by bsideup** [comment]
Hi!

This is just extraction MongoDBDataHandler interface from it's default realisation. It's really helpful for custom mongo data handling

**Comment by mevivs** [comment]
Moving for release > 2.9

**Comment by bsideup** [comment]
Ok, sure! Good luck with 2.9 release btw! :)

**Pull request closed without merging**
