### PR TITLE
Kundera 2.0.5

### PR DESCRIPTION
**Pull request by kcarlson**
Fixes for using UUIDs as pks. Ran tests in kundera-examples using uuids as pks as to verify cascading persists and joins.

### CODE REVIEW

**Comment by mevivs** [comment]
Thanks Kristoffer. I will have a look. However these changes will be merged in 2.0.6 branch, so i will change pom versions manually for the same.

Great. thanks for contribution.

-Vivek

**Comment by mevivs** [comment]
Hi Kristoffer,
Could you please raise this for 2.0.6 branch? As 2.0.5 is already freezed one and current developement is going on 2.0.6?

**Comment by kcarlson** [comment]
I don't think I'll make it until the code freeze, sorry.

**Comment by mevivs** [comment]
Could you please arrange it sometime in next week? We have extended code freeze till 6th April due to some urgent fixes. So we can incorporate changes as well.

Also just to share with you, We have automated test cases in kundera-examples, so probably you don't need worry about server and schema setup anymore!

**Comment by kcarlson** [comment]
Sorry I haven't responded, been on vacation. We have actually decided to use an in-house dao solution for cassandra, so unfortunately I will not have time to merge my changes into 2.0.6 and open another pull request. Sorry. Best of luck with the project!!

**Comment by mevivs** [comment]
Aah OK. sad to hear that you decided for some other solution. Anyway i have merged some of your work back into Kundera. Thanks for making such contribution. In case if you could share what made your team to move to look for other solution, that feedback will definitly help.

-Vivek

**Comment by kcarlson** [comment]
Ok. no problem.

The reason was that I really needed to use composite columns (storing data in column names instead of in the actual column) for various sorting, slicing, and some odd use cases. I also needed columns/objects to be dynamic. For instance, when you create an entity, a restriction on the columns is created since they are "hard-coded". I created a solution for this, but our code was becoming more fragmented with two interfaces to pelops->cassandra, so we decided to only use our in-house solution. 

I also needed some other things, like ttl and dist counters.

Our solution is somewhat similar in the way that data is marshalled and unmarshalled into/out-of cassandra's storage. It is all done using Spring 3. There's basically a Dao interface with, get(PK), put(T), remove(T), etc...

Another reason was writing sql-like commands to retrieve data makes you think more like sql instead of nosql. I know that cassandra has a cql interface, but this, in my opinion, is still very experimental and requires a lot of work to incorporate many other aspects of nosql into their query language.

**Comment by mevivs** [comment]
Hmm. That's why recently we have refactored client api in kundera to add such supports! It is a very valid point and considering JPA is written keeping RDbMS in mind, NoSql support definitly needs an extension. Hopefully future release of kundera will cover up on this part!

-Vivek

**Comment by kcarlson** [comment]
I haven't really kept up with changes. What support are you referring to (composite cols, dyn cols, ttl, counters)?

**Comment by mevivs** [comment]
yes. we are planning to include such supports as well as CounterColumnType etc after 2.0.6
Idea is to leverage db specific client and provide such stuff, as doing it in JPA way is bit difficult and defeats purpose for NoSqls. 2.0.6 has already complelty decoupled kundera-cassandra(and others) from kundera-core .

-Vivek

**Comment by kcarlson** [comment]
Cool! Sounds like the right approach.

**Comment by mevivs** [comment]
Hi,
If you want to add anything to wishlist, feel free to add at: https://github.com/impetus-opensource/Kundera/issues/63

**Comment by mevivs** [comment]
---------- Forwarded message ----------
From: Amry amresh1002@gmail.com
Date: Wed, Jul 25, 2012 at 4:41 PM
Subject: {kundera-discuss} Kundera 2.0.7 Released
To: kundera-discuss@googlegroups.com

Hi All,

We are happy to announce release of Kundera 2.0.7.

Kundera is a JPA 2.0 based, object-datastore papping library for NoSQL
datastores. The idea behind Kundera is to make working with NoSQL Databases
drop-dead simple and fun. It currently supports Cassandra, HBase, MongoDB
and relational databases.

## Major Changes in this release:
- HBase 0.92.1 migration
- Hadoop 1.0.2 migration
- Cassandra 1.1.2 migration
- MongoDB 2.0.4 migration
- JPA EntityTransaction commit and rollback
- JTA Transactions integration over web server
- Kundera-REST API
- Support for Counter column in cassandra
- Inverted wide-row indexing support for Cassandra
- Login Authentication support for Cassandra and MongoDB
- Filters and filters list for HBase
- Deprecated Lucene based indexing for HBase.
- Datastore specific configuration files for specifying:
  - Replication factor
- Placement strategy
- Consistency level per operation.
  - Counter column family configuration
- Inverted indexing switch
- Zookeeper host and port
  - Hbase column family configurations
- MongoDB servers list, read preference and socket timeout. ...etc.

To download, use or contribute to Kundera, visit:
http://github.com/impetus-opensource/Kundera
Latest released tag version is kundera-2.0.7. Kundera maven libraries are
now available at:
https://oss.sonatype.org/content/repositories/releases/com/impetus

Sample codes and examples for using Kundera can be found here:
http://github.com/impetus-opensource/Kundera-Examples
and
https://github.com/impetus-opensource/Kundera/tree/trunk/kundera-tests

Thank you all for your contributions!

Regards,
Kundera Team.

**Pull request closed without merging**
