### PR TITLE
Fix a secondary index field ref spec problem.

### PR DESCRIPTION
**Pull request by georgkoester**
Queries for sec indexes were not working.

### CODE REVIEW

**Comment by georgkoester** [comment]
By the way, I was trying to make this work (Cassandra):
public class User {
    // One to many, ids inline in row
    @OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.EAGER)
    private List<Role> roles = new ArrayList<Role>();
}

Expecting to have the role_ids as (sub?) columns in the User-row. But no, he want's a column for the User-id in Role. That's clearly not a good fit. Is it possible to get the role-ids into the user row? (I'm using Cassandra)

**Comment by mevivs** [comment]
Hi,
Could you please verify it with trunk branch? It should work with latest trunk branch.

-Vivek

**Comment by georgkoester** [comment]
Hi Vivek,

9 hours ago it was not working. Take a look at my change, in trunk
fieldName contains 'User.name' and this then is used to query Cassandra -
which then complains that the field has no index. Cassandra only knows of
'name', not 'User.name'. After my change the secondary index query is
working.

Sorry I didn't write a test, just doing evaluation.

Different Problem: I was trying to get the association mapping to work
which I was talking about. I want something like this in Cassandra:

user: {
     name: "blah",
     roleids: ["asfasdf", "jkljl"....]
}

Which should be mapped as (pseudocode):
@Entity
class User {

@Column(name="name")
String name;

@Column(name="roleids")
List<Role> roles;
}

Cheers,
Georg

On Thu, May 24, 2012 at 7:36 AM, Vivek Mishra <
reply@reply.github.com

**Comment by mevivs** [comment]
Hi Georg,
Seems this change is still lying on my machine and somehow i missed to push this one :)  As this is more generic change and require for other DBs, so changing it for CassQuery will resolve it partially. I will update you on this ASAP.

For other problem:
i think it is somewhat similar to: https://github.com/impetus-opensource/Kundera/issues/65

Thanks,
Vivek

**Comment by mevivs** [comment]
Commited just now for revision number: 445a4c7c0aeac6fbfe432022f9b8dadc612fb76e ,Thanks Kuldeep.

Hi Georg,
Please verify if it works for you.

Cheers,
Vivek

**Comment by georgkoester** [comment]
Thanks, I'll have a look at it later today!

On Thu, May 24, 2012 at 9:51 AM, Vivek Mishra <
reply@reply.github.com

**Comment by georgkoester** [comment]
You fixed the secondary index trouble, thanks.

**Pull request closed without merging**
