### PR TITLE
Support for @MappedSuperclass and @Inheritance when validating and read metadata for @Id

### LINKED ISSUE #55: Please add support for JPA @Inheritance
We would like to utilize Entity inheritance in our classes.  Please refer to the forum group discussion for more information.

https://groups.google.com/forum/?fromgroups#!topic/kundera-discuss/6B40tBFvWHk

### PR DESCRIPTION
**Pull request by smecsia**
This change partly resolves #55 and #56 in the terms when it is required to use @MappedSuperClass and to have an @Id field in it (it just reads the fields from the entity class hierarchy instead of reading them from the main entity class directly).
I'm not sure if you are going to merge this request, but these issues are really blockers for us, so we have to use our own fixed Kundera version temporarily.

### CODE REVIEW

**Comment by smecsia** [comment]
It was also the issue with the validation of no-args constructor for an abstract class which has the @Inheritance annotation. 

BTW, I want to point out, that we don't use inheritance for the entities that are stored in noSQL DB. So our entities with inheritance are handled by Hibernate only. But since we have multi-persistence data storage, we're getting the exceptions from Kundera's validators for our RDBMS entities.

**Comment by mevivs** [comment]
Another alternative is , defining entities specific to Kundera should work for you. also define as:

```
<exclude-unlisted>true</exclude-unlisted>

```

Mapped super class support is definitly needed
-Vivek

**Comment by threeseed** [comment]
+1 for mapped super class support. Desperately needed.

**Comment by mevivs** [comment]
Looking into pull request.

-Vivek

**Comment by mevivs** [comment]
Target for 2.4 release.

-Vivek

**Comment by pires** [comment]
@mevivs how's this? Has it been merged to 2.4?

**Comment by mevivs** [comment]
Not yet merged. Pull request is actually a partial fix and we need to start and incorporate the same along with proper fix. 

-Vivek

**Comment by subes** [comment]
Also very interested in seeing this! Any updates about it? 

I think even only supporting this for Kundera-RDBMS would be a great help, so we can use RDBMSClientFactory with our working hibernate entities that are based on @MappedSuperClass. For all other cases @MappedSuperClass support is not needed as urgently. This is because the NPE is a show-stopper for using Kundera on top of a working hibernate setup in order to integrate NoSQL entities next to existing RDBMS entities.

**Comment by mevivs** [comment]
WIP, Planned for 2.8 release. 

-Vivek

**Comment by subes** [comment]
Yay :) tell me when there is something testable in trunk and I will verify
if it works for me.
Am 10.09.2013 09:07 schrieb "Vivek Mishra" notifications@github.com:

**Comment by mevivs** [comment]
Support added in current trunk and releasing with 2.8

**Pull request closed without merging**
