### PR TITLE
Kundera 2.0.5

### PR DESCRIPTION
**Pull request by zenbones**
1) Added a proper .gitignore file, so that git won't be trying to add target directories from maven, or idea project files (and someone can add eclipse project files if needed)
2) Replace uses of log4j with uses of slf4j, which presents no end-point logger. It's up to the end-user to include the proper slf4j library (all available via maven) as needed. The only log4j usage is in the test cases, which is fine, and log4j specific dependencies are now marked as test scope.

Not sure how you setup logging for test, and am not a log4j user, so you should check that your logging works, and make any adjustment needed, but all tests passed on the build.

### CODE REVIEW

**Comment by mevivs** [comment]
Hi V.S,
Can you please review it ?

**Comment by mevivs** [comment]
Thanks David.

**Comment by vishri** [comment]
The changes are good to go. Amry, please merge them.

**Comment by mevivs** [comment]
I see that kundera-core pom is changed to remove dependency for slf4J and it is added with scope test within kundera-cassandra. Although it is required for different code files. Like Mongo,RDBMS clientFactory.

Some how this dependency is getting fetched from other library, so it is working. But i think your changes must have it in kundera-core without scope "test". 

Vivek

**Comment by zenbones** [comment]
The slf4j dependency is there, and is compile scoped. The log4j dependency has been moved to the test scope. They are two completely different libraries.

If another project requires a dependency, if you need to include it, it should be marked 'optional'. However, all code compiles, and as far as I can tell, all tests run with the pom files as I've corrected them, and you're no longer foisting log4j onto your users.

David

Sent from my HTC on the Now Network from Sprint!

----- Reply message -----
From: "mevivs" reply@reply.github.com
Date: Wed, Jan 18, 2012 1:51 am
Subject: [Kundera] Kundera 2.0.5 (#22)
To: "David Berkman" david.berkman@grenadefish.net

I see that kundera-core pom is changed to remove dependency for slf4J and it is added with scope test within kundera-cassandra. Although it is required for different code files. Like Mongo,RDBMS clientFactory.

Some how this dependency is getting fetched from other library, so it is working. But i think your changes must have it in kundera-core without scope "test". 

Vivek

---

**Comment by mevivs** [comment]
Cool. missed it in kundera-pom while review.  Changes are commited in 2.0.5.

Closing it

**Pull request closed without merging**
