### PR TITLE
Removed filenames without camel case.

### LINKED ISSUE #268: Problem with git clone on Mac and possibly Windows
I'm really wanting to contribute to Kundera but right now I'm unable to provide even the simplest change because every time I clone the project, a bunch of files show up as _modified_.

```
macpro-pires:kundera pires$ git st
# On branch trunk
# Your branch is ahead of 'origin/trunk' by 1 commit.
#
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/StudentCassandraBooleanTest.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/StudentCassandraByteTest.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/StudentCassandraDoubleTest.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/StudentCassandraFloatTest.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/StudentCassandraLongTest.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/StudentCassandraShortTest.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/entities/StudentCassandraBoolean.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/entities/StudentCassandraByte.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/entities/StudentCassandraDouble.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/entities/StudentCassandraFloat.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/entities/StudentCassandraLong.java
#   modified:   kundera-cassandra/src/test/java/com/impetus/client/crud/datatypes/entities/StudentCassandraShort.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/StudentHBaseBooleanTest.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/StudentHBaseByteTest.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/StudentHBaseDoubleTest.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/StudentHBaseFloatTest.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/StudentHBaseLongTest.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/StudentHBaseShortTest.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/entities/StudentHBaseBoolean.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/entities/StudentHBaseByte.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/entities/StudentHBaseDouble.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/entities/StudentHBaseFloat.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/entities/StudentHBaseLong.java
#   modified:   kundera-hbase/src/test/java/com/impetus/client/hbase/crud/datatypes/entities/StudentHBaseShort.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/StudentMongoBooleanTest.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/StudentMongoByteTest.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/StudentMongoDoubleTest.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/StudentMongoFloatTest.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/StudentMongoLongTest.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/StudentMongoShortTest.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/entities/StudentMongoBoolean.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/entities/StudentMongoByte.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/entities/StudentMongoDouble.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/entities/StudentMongoFloat.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/entities/StudentMongoLong.java
#   modified:   kundera-mongo/src/test/java/com/impetus/client/crud/datatypes/entities/StudentMongoShort.java
#   modified:   kundera-oracle-nosql/src/test/java/com/impetus/client/oraclenosql/datatypes/entities/StudentOracleNoSQLBoolean.java
#   modified:   kundera-oracle-nosql/src/test/java/com/impetus/client/oraclenosql/datatypes/entities/StudentOracleNoSQLByte.java
#   modified:   kundera-oracle-nosql/src/test/java/com/impetus/client/oraclenosql/datatypes/entities/StudentOracleNoSQLDouble.java
#   modified:   kundera-oracle-nosql/src/test/java/com/impetus/client/oraclenosql/datatypes/entities/StudentOracleNoSQLFloat.java
#   modified:   kundera-oracle-nosql/src/test/java/com/impetus/client/oraclenosql/datatypes/entities/StudentOracleNoSQLLong.java
#   modified:   kundera-oracle-nosql/src/test/java/com/impetus/client/oraclenosql/datatypes/entities/StudentOracleNoSQLShort.java
#   modified:   kundera-oracle-nosql/src/test/java/com/impetus/client/oraclenosql/datatypes/tests/StudentOracleNoSQLBooleanTest.java
#   modified:   kundera-oracle-nosql/src/test/java/com/impetus/client/oraclenosql/datatypes/tests/StudentOracleNoSQLByteTest.java
#   modified:   kundera-oracle-nosql/src/test/java/com/impetus/client/oraclenosql/datatypes/tests/StudentOracleNoSQLDoubleTest.java
#   modified:   kundera-oracle-nosql/src/test/java/com/impetus/client/oraclenosql/datatypes/tests/StudentOracleNoSQLFloatTest.java
#   modified:   kundera-oracle-nosql/src/test/java/com/impetus/client/oraclenosql/datatypes/tests/StudentOracleNoSQLLongTest.java
#   modified:   kundera-oracle-nosql/src/test/java/com/impetus/client/oraclenosql/datatypes/tests/StudentOracleNoSQLShortTest.java
```

I think this is related to this issue with case-sensitive filenames, http://stackoverflow.com/questions/5009096/files-showing-as-modified-directly-after-git-clone

I'm using MacOs 10.8.3 with Git 1.8.2.3.

### PR DESCRIPTION
**Pull request by pires**
Fixes #268

Signed-off-by: Paulo Pires pjpires@gmail.com

### CODE REVIEW

**Comment by pires** [comment]
This has been tested by cloning my fork on two Mac and one Linux systems.

**Comment by mevivs** [comment]
Hi,
Did you remove or renamed those test cases? Test cases such as "StudentMongolong" is for primitive "long" data types. So we need to rename them

-Vivek

**Comment by pires** [comment]
Aaaaaah, so you **do** need those files. I didn't understand before that there was that differentiation. My bad! I'm closing the pull-request and waiting on your fix then. Thanks and sorry for the mess-up.

**Comment by pires** [comment]
I'd recommend some renaming like **CassandraLongPrimitiveTest** and **CassandraLongWrapperTest**, for instance.

**Comment by mevivs** [comment]
+1. Do you mind to raise a new pull request with all such renamed ones? You already a list of such files available in your pull request?

-Vivek

**Comment by pires** [comment]
I can provide a fix, if we agree on the naming. Would you agree with the proposal in my previous comment?

**Comment by mevivs** [comment]
I am fine with it.
 :+1:

**Pull request closed without merging**
