### PR TITLE
fixed npe in OneToManyRelationMetadataProcessor

### PR DESCRIPTION
**Pull request by trajar**
When trying to use inheritance and one-to-many collections I keep getting null pointers.  This commit seems to do the trick.  Stack trace below: 

java.lang.NullPointerException
    at com.impetus.kundera.metadata.processor.relation.OneToManyRelationMetadataProcessor.addRelationIntoMetadata(OneToManyRelationMetadataProcessor.java:93)
    at com.impetus.kundera.metadata.processor.TableProcessor.addRelationIntoMetadata(TableProcessor.java:181)
    at com.impetus.kundera.metadata.processor.TableProcessor.populateMetadata(TableProcessor.java:147)
    at com.impetus.kundera.metadata.processor.TableProcessor.process(TableProcessor.java:87)
    at com.impetus.kundera.metadata.MetadataBuilder.buildEntityMetadata(MetadataBuilder.java:131)
    at com.impetus.kundera.configure.MetamodelConfiguration.scanClassAndPutMetadata(MetamodelConfiguration.java:391)
    at com.impetus.kundera.configure.MetamodelConfiguration.loadEntityMetadata(MetamodelConfiguration.java:230)
    at com.impetus.kundera.configure.MetamodelConfiguration.configure(MetamodelConfiguration.java:102)
    at com.impetus.kundera.configure.Configurator.configure(Configurator.java:65)
    at com.impetus.kundera.KunderaPersistence.initializeKundera(KunderaPersistence.java:109)
    at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:81)
    at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)

### CODE REVIEW

**Comment by kkmishra** [comment]
Hi,
Id attribute should not be null, A validation has been added for the same in current trunk branch,
Please verify.

Could you please share your scenario?

Thanks
Kuldeep

**Comment by trajar** [comment]
I think it might have something to do with the order in which the processors look at relationships and entity inheritance.  Specifically, at the point of the NPE it looks like the related class hasn't been correctly processed yet and doesn't have its inherited id attribute processed.  Without the commit/fix, Kundera fails when processing the one-to-many relationship with the above state trace.  My scenario below: 

An abstract base class (with the id attribute):

```
@MappedSuperclass
abstract public class GuidDomainObject extends DomainObjectAdapter
{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", updatable = false, nullable = false)
    private Long id = null;
}
```

An abstract/common intermediary profile class: 

```
@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@Table(name = "social_profile")
@DiscriminatorColumn(name = "type", length = 64, discriminatorType = DiscriminatorType.STRING)
abstract public class SocialProfile extends GuidDomainObject
{
    @Column(name = "type", nullable = false, updatable = false)
    private String userType;

    @ManyToOne(optional = false)
    @JoinColumn(name = "user_account_id", nullable = false)
    private UserAccount account;
}
```

A concrete profile class: 

```
@Entity
@DiscriminatorValue(TwitterProfile.TYPE)
public class TwitterProfile extends SocialProfile
{
    protected static final String TYPE = "twitter";

    @Column(name = "twitter_id", updatable = false)
    private long twitterId;

    @Column(name = "twitter_user", length = 128)
    private String twitterUser;
}        
```

A concrete account class containing the one-to-many relationship:

```
@Entity
@Table(name = "user_account")
public class UserAccount extends GuidDomainObject
{
    @Column(name = "display_name", length = 128)
    private String displayName = null;

    @Column(name = "email", length = 128, unique = true)
    private String email = null;

    @OneToMany(mappedBy = "account")
    private Set<SocialProfile> profiles = new HashSet<>();
} 
```

**Comment by mevivs** [comment]
Exact cause behind this issue is support for Abstract entity class was not available with Kundera. This has been added in current trunk branch. Please verify.

-Vivek

**Comment by mevivs** [comment]
@trajar 
Could you please verify with latest released 2.9?

-Vivek

**Comment by trajar** [comment]
Looks like the 2.9 release addressed this issue.  Thanks for looking into it @mevivs - much appreciated.

**Pull request closed without merging**
