### PR TITLE
Kundera 2.0.5

### PR DESCRIPTION
**Pull request by kcarlson**
I made a number of fixes associated with UUIDs as row keys and column values.

Please review and advise.

Thanks!!

### CODE REVIEW

**Comment by mevivs** [comment]
i will have a look on this. Thanks Again

-Vivek

**Comment by mevivs** [comment]
I am reviewing it and will be merged by today.

Thanks Carlson for good contributions.

-Vivek

**Comment by mevivs** [comment]
119f7cb  :

if(!idxColumnPresent && !idColumn.equalsIgnoreCase(fieldName))
{
idxColumnPresent = true;
}

Why do we need to have another boolean variable, Could you please elaborate issue faced for making this change?

**Comment by mevivs** [comment]
080e9fd

Please add log statements and avoid e.printStackTrace(), we are already working on removing these things from current code base.

-Vivek

**Comment by mevivs** [comment]
5d42f07

Why do we need to pull "pelops" dependency in kundera-core! As pelops is very much specific to cassandra.
Any such changes in kundera-core must be highly avoided.

Please review this change.

-Vivek

**Comment by mevivs** [comment]
d31bf8d

Please review as per previous comment.

-Vivek

**Comment by mevivs** [comment]
Thanks for these contributions.
However Kundera supports MongoDB, HBase,Mysql other than cassandra. So these changes needs to be made keeping any impact they might have on other components.

There is seperate test project Kundera-Examples with proper test cases to validate these changes:

https://github.com/impetus-opensource/Kundera-Examples/tree/Kundera-Examples-2.0.5/src/test/java/com/impetus/kundera/examples/crossdatastore

https://github.com/impetus-opensource/Kundera-Examples/tree/Kundera-Examples-2.0.5/src/test/java/com/impetus/kundera/examples/crud

I suggest, if you could verify your changes against available test cases.

Thanks again.

-Vivek

**Comment by kcarlson** [comment]
Yes, once again the changes past 5d42f07fcd6dccfac2eaf3c1ceb80f5489c62623 weren't officially intended for the pull. Sorry about that.

I will take a look at the kundera-examples test cases.

**Comment by mevivs** [comment]
Thanks a lot Kristoffer.

in case if you could raise a pull request for changes which needs to be merged after all your fixes. I will put this action point on myself to quickly merge them in kundera

-Vivek

**Comment by mevivs** [comment]
Hi Kristoffer,
Please let me know, once you are ready with your pull request. Changes which needed to merged!

-Vivek

**Comment by kcarlson** [comment]
Hmm, I guess I keep on changing things when I encounter something that doesn't work as I need it. :) Everything I've done works correctly in regards to cassandra (I have a bunch of tests outside of kundera for my specific application which verify my changes, once again, at least in cassandra). I haven't run all the tests in kundera-examples yet since I don't have all the databases installed on my dev workstation. So to answer your question, they are ready once the changes have been verified running the kundera-example test suite. I should hopefully be able to get around to this tomorrow.

**Comment by mevivs** [comment]
Great to hear that.

I haven't run all the tests in kundera-examples yet since I don't have all the databases installed on my dev workstation.
<vivek> You can try it atleast on two(e.g. mysql, Cassandra) to get a feeling if it is running or not, However we are working on CI integration over kundera-examples, in case if something is broken</vivek>

Your changes to CassQuery(related to range query) and PelopsClient(related to null on getSlice) are definitly needed apart from UUID changes.

Take your time. Once you are done we can work together to check-in your stuff.

Cheers,
Vivek

**Comment by kcarlson** [comment]
Do you have any scripts to populate the databases (mysql,cassandra) with the data needed for the testcase in UserAddressDaoTest?

**Comment by mevivs** [comment]
Please ignore this test. It is going to be deleted.
Rest i assume all other test should work for you.
For mysql: if you enable "ddl_auto_create" that should do the trick for you.

**Comment by kcarlson** [comment]
ok. Which testcase would you say is best for verifying cross-datastore with mysql/cassandra?

**Comment by mevivs** [comment]
https://github.com/impetus-opensource/Kundera-Examples/tree/Kundera-Examples-2.0.5/src/test/java/com/impetus/kundera/examples/crossdatastore

https://github.com/impetus-opensource/Kundera-Examples/tree/Kundera-Examples-2.0.5/src/test/java/com/impetus/kundera/examples/crud

These are what are we following for junit test cases. If you exclude UserAddressDaoTest.java, rest should work for you.

BTW, i did check in lots of stuff (related to core loading). I hope it does not break anything for you!

Cheers,
Vivek

**Comment by mevivs** [comment]
In case you want to discuss something my gtalk id is vivek.niit@gmail.com.

-Vivek

**Comment by mevivs** [comment]
I have commited some changes for test case. Those should help you out for running kundera-examples.

-Vivek

**Comment by kcarlson** [comment]
Great, thanks so much! Sorry I haven't been able to get around to setting up and testing.

Also, the last commit has a very important bugfix (see commit e6dcb72a3f4a8c9afbecc6b88ee34a8f10d6c6b6).

**Comment by mevivs** [comment]
Yes. i saw it. Thanks again for one more contribution

-Vivek

**Comment by kcarlson** [comment]
Hi. Finally got around to testing.

PersonTest: 
  Both cassadra and mysql unit tests pass. However, onInsertCassandra will most likely fail at line 145 if the random partitioner is used. 

PickrBaseTest:
  I had to comment out cleanLuceneDirectory since I changed my dependencies to 2.0.5.

  PickrTestBi_1_M_1_M fails @ line 64 due to the addition of PHOTOGRAPHER_ID as a scalar to the SQLQuery object in HibernateClient @ line 625, throwing the exception @ line 629. This doesn't have anything to do with my changes though.

  PickrTestBi_M_M_1_1 fails @ line 168 due to the relationships to ALBUM not being persisted in the database. For example, when provisioning the users, the PHOTOGRAPHER.ALBUM_ID = NULL for all users as well as PHOTO.ALBUM_ID = NULL for all photos. In ALBUM all PHOTOGRAPHER_IDs are NULL as well. So there is an issue with album relationships that needs to be investigated. Once again, I don't think that these have anything to do with my changes.

Hopefully this is useful to you. I would like to draw the conclusion that the tests showed the changes made have not had a negative impact on kundera's cross-datastore capabilities. But please have a look, I may have overlooked, or misinterpreted something.

Thanks for the advice!

**Comment by mevivs** [comment]
Thanks Kristoffer.
I will have a look.

Cheers,
Vivek

**Comment by mevivs** [comment]
Hi,
Shall i assume these as your final changes to pushed in?

-Vivek

**Comment by kcarlson** [comment]
I have one more thing to check regarding UUIDs. I think I have to make some (small) changes involving joins and foreign keys. I think I forgot to add the special ByteUtils that take UUIDs into consideration in those functions.

**Comment by mevivs** [comment]
Okay. Can you please raise a seperate pull request once you are done with your changes?

-Vivek

**Comment by kcarlson** [comment]
Will do. Shall this pull request be closed then?

**Comment by mevivs** [comment]
Yes. i think that should be fine.

**Pull request closed without merging**
