### PR TITLE
Allow persistence unit to be configured at runtime

### PR DESCRIPTION
**Pull request by masha256**
This pull request solves the follow two issues:

https://github.com/impetus-opensource/Kundera/issues/133
https://github.com/impetus-opensource/Kundera/issues/121

### CODE REVIEW

**Comment by xamry** [comment]
This change is not going to work in Polyglot persistence case and is going to bring undersirable results in multithreaded environement. This changes requires some major design changes. This is postponed to next release.

**Comment by masha256** [comment]
What is polyglot persistence? Passing a list of several persistence units to the factory to have them initialized at once? If so, it seems that it is up to the person initializing the persistence manager - and they can choose which properties they want to override, etc... 

As for multi threaded, what doesnt work? Its just a map thats passed around, and again, if the client of kundera needs multithread safe, they would pass in a ConncurentHashMap, no?

**Comment by impetus-opensource-admin** [comment]
What is polyglot persistence? Passing a list of several persistence units to the factory to have them initialized at once? If so, it seems that it is up to the person initializing the persistence manager - and they can choose which properties they want to override, etc...

```
<vivek> In case of polyglot persistence user will initialize emf as "Persistence.createEntityManagerFactor(pu1,pu2,pu3)"

Each pu belongs to different client means different database, so common set of properties cannot be applied to all of them. Hence a pattren is needed to define set of properties.

</vivek>
```

As for multi threaded, what doesnt work? Its just a map thats passed around, and again, if the client of kundera needs multithread safe, they would pass in a ConncurentHashMap, no?

```
<vivek> 
 Currently we have found some issue with access to EntityManagerFactory instance across the different sessions in multithreaded environment, and so we need to include a mechanism to load/unload these properties(along with other stuff) as well.
</vivek>
```

Hope it helps

-Vivek

**Comment by masha256** [comment]
I still think there is value in this patch. Think of all the people not using polyglot. And for those who are, there is no reason they have to override all properties. The documentation could simply say be careful not to override those properties needed for polyglot. 

And if this is a really big concern, I can change the map that gets passed in so that it is keyed off the persistence unit name and the value is another map containing the override properties for that single persistence unit.

As for multithreaded, it sounds like the issues are outside of the patch I made, so why not give the much needed functionality of this patch, and then when doing the general EntityMangerFactory cleanup for multi-threaded, clean up the code to deal with properties then.

Again, I just think there is more value this patch provides than takes away. In those special case situations, just make sure it is documented well.

**Comment by mevivs** [comment]
Hi,
Of course this change is really required. We will merge and release this change with 2.3. Team is analyzing to add changes around this pull request, so that it can cater all scenarios.  

Issues discussed around this are just an extension to this problem.

Cheers,
-Vivek

**Comment by mevivs** [comment]
Amresh,
Please look into this.

Thanks,
-Vivek

**Comment by mevivs** [comment]
Patch is only half way through, but good to go, except:

We should not populate these properties into persistenceUnitMetadata, Though better to pass it to client or EntityManager. PersistenceUnitMetadata should only be mapped with persistence.xml settings.

As i am working to get it done for polyglot as well. So i might need to merge it manually to exclude Pumetadata change.

Cheers,
-Vivek

**Comment by masha256** [comment]
I am not sure why you wouldnt want to use PersistenceUnitMetadata. One of the settings we want to override programmatically is the host/port information. If you only pass this to the EntityManger, it has already created the connection to the backend.

**Comment by mevivs** [comment]
It definitly fits for 1-2 aspects. 2 Reasons:

1) Supplied set of properties are not meant for persistence unit metadata, these are for client factory or client itself.
These set of properties are meant for Client instantiation or client level operations, i guess it would be better to simply delegate them to client(factory) itself!

2)  There is an identified issue ( related to loading of entity manager factory)which may cause lead to another issues, if we modify persistence unit metadata straight way by supplied set of properties

**Comment by mevivs** [comment]
Hi All,
This change has been pushed into current trunk branch. As automatic merging was not possible so this pull request is manually merged partially. I will be updating wiki for this later.

Thanks for your contribution.

Cheers,
-Vivek

**Comment by mevivs** [comment]
Closing as it is manually merged and working fine now.

**Pull request closed without merging**
